language: node_js
env:
- REACT_V=react@16.0.x REACT_DOM_V=react-dom@16.0.x
- REACT_V=react@16.1.x REACT_DOM_V=react-dom@16.1.x
- REACT_V=react@16.2.x REACT_DOM_V=react-dom@16.2.x
- REACT_V=react@16.3.x REACT_DOM_V=react-dom@16.3.x
- REACT_V=react@16.4.x REACT_DOM_V=react-dom@16.4.x
- REACT_V=react@16.5.x REACT_DOM_V=react-dom@16.5.x
- REACT_V=react@16.6.x REACT_DOM_V=react-dom@16.6.x
- REACT_V=react@16.7.x REACT_DOM_V=react-dom@16.7.x
- REACT_V=react@16.8.x REACT_DOM_V=react-dom@16.8.x
- REACT_V=react@16.9.x REACT_DOM_V=react-dom@16.9.x
notifications:
  email: false

# Install reqd react and react-dom version for each matrix
before_script:
  - echo $REACT_V $REACT_DOM_V # log react and react-dom versions
  - npm i --no-save $REACT_V $REACT_DOM_V  # install them

script:
  - npm run test
  - npx codecov
